### ISSUE TITLE
Remember last used directory when saving

### ISSUE THREAD

**Issue by jarradraumati** [danyill/oscd-save-as#2]
At present, the `startIn` option is set to `download`.

One feature which would be nice is to remember the directory path that was used last to save by default.

It looks like it might be possible with a directory handle, but I have not looked in great detail.

https://developer.chrome.com/docs/capabilities/web-apis/file-system-access#specifying_a_suggested_file_name_and_start_directory

**Comment by danyill** [comment]
I like the idea, but I believe there is no way to get from a fileHandle to a directoryHandle, mostly for security reasons. Or if there is I can't find it.

If we had asked for a directory to begin with then that would be fine but then we wouldn't have a save file picker (so if we could rename our project in open-scd we could do that).

It seems like with IndexedDB there would be a way to remember the particular handle across reloads of the plugin but that seems a bit dangerous to me.

However a PR would be most welcome :stuck_out_tongue_winking_eye:

**Comment by jarradraumati** [comment]
I think the change is simple.
If `startIn` is not specified, the browser seems to remember the last directory that was used to save the file, rather than always defaulting to the users downloads directory.

At least this is the behaviour I see on Google Chrome `Version 127.0.6533.72 (Official Build) (64-bit)`
